name: Java CI with Gradle

on:
  push:
    paths-ignore:
      - "README.md"

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk
      options: --user root

    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: check build

      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
            fabric/build/libs/
            forge/build/libs/